name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Globally install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Laravel Pint
        run: pint

      - name: Push Back to Repo
        run: |
          git config user.name "gh-actions"
          git config user.email "gh-actions@laracasts.com"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push
