name: Laravel Pint

on:
  pull_request

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Globally install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Laravel Pint
        run: pint

      - name: Push Back to Repo
        run: |
          git config user.name "gh-actions"
          git config user.email "gh-actions@laracasts.com"
          git commit -m "Laravel Pint"
          git push
