name: "Code Cleanup"

on:
  pull_request:
    branches:
      - main

jobs:
  laravel-pint:

    name: "Laravel Pint"
    runs-on: ubuntu-latest
    env:
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
      cache-key: cache-v1
    steps:
      # Checkout our codebase
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Needed for committing the code back to the PR

      # Set up PHP
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 8.3
          extensions: ${{ env.extensions }}
          key: ${{ env.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.3
          extensions: ${{ env.extensions }}
          tools: composer:v2
      # Global installation of Pint
      - name: "Install Pint"
        run: composer global require laravel/pint
      # Install composer dependencies
      - name: "Install Project Dependencies"
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # Execute Laravel Pint
      - name: "Execute Laravel Pint"
        run: "pint"
      # Commit back to repo
      - name: "Commit Changes"
        # Exit 0 required to ensure no changes don't cause an error
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Code Cleanup via Laravel Pint" || exit 0
          git push

