name: "Code Cleanup Using Pint"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-pint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install -q --prefer-dist --no-progress

    - name: Install Pint
      run: composer global require laravel/pint

    - name: Run Pint
      run: pint

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "bot@laracasts.com"
        git add .
        git commit -m "Code cleanup using Pint"
        git push
