name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    env:
      PHP_VERSION: '8.3'
      CACHE_KEY: extension-cache-v1
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact
